<?php

namespace App\Service\Archive;

use App\MHT;
use App\Service\CompilerV2\Manhunt2;
use App\Service\Helper;
use App\Service\NBinary;
use Symfony\Component\Finder\Finder;

class Dir extends Archive
{

    public $name = 'Audio Names';

    public static $supported = 'dir';

    /**
     * Generated by the given usage inside the SRCE function calls
     */
    public $speech = [
        [
            "level" => "A01_Escape_Asylum",
            "names" => [
                "LEO31",
                "LEO32",
                "LIFT1",
                "WATERDRIP",
                "MLT1",
                "MLT2",
                "MLT3",
                "MLT9",
                "ML11",
                "WACKO3",
                "SYR1",
                "LEO53",
                "DAN11",
                "LEO50",
                "DAN15",
                "DAN13",
                "LEO9",
                "ET1",
                "ET2",
                "RADIO1",
                "ET3",
                "RADIO2",
                "ET4",
                "RADIO3",
                "ET2_A",
                "DANR1",
                "LEO45",
                "NATTACK5",
                "FBEDS",
                "LEO16A",
                "SRE2",
                "LEO34",
                "LN2",
                "SFAIL2",
                "LN3",
                "SFAIL3",
                "LEO33",
                "LN1",
                "LEO36",
                "LOON1",
                "SFAIL1",
                "HANG",
                "ML12",
                "LEO16",
                "WOM2",
                "DYINGGUY",
                "WT2",
                "AV1DS1",
                "INMATE2",
                "LEO35",
                "LEO37",
                "INMATE1",
                "INMATE3",
                "STEAM",
                "DAN10",
                "PUKE",
                "SLIDER",
                "XTUT1",
                "LEO8",
                "LEO49",
                "WH01",
                "WH02",
                "WH03",
                "WH04",
                "WH05",
                "WH06",
                "PICK1",
                "PICK2",
                "NUA3",
                "NUA4",
                "BEAT2",
                "PIC1_A",
                "SPARKS",
                "AMBSHOT",
                "LEO10",
                "DAN6",
                "LEO40",
                "LGHTN1",
                "LGHTN2",
                "LGHTN3",
                "BLOCK",
                "ESCAP",
                "WT4",
                "WT5",
                "WT6",
                "LOONIES2",
                "TD1",
                "NUH1",
                "TD2",
                "NUH2",
                "TD3",
                "NURSELIFT",
                "LOONIES",
                "DRV6",
                "DRV7",
                "TRUCK",
                "LEO19",
                "END1_A",
                "END2_A",
                "DRV1_A",
                "DRV2_A",
                "DRV3_A",
                "DRV4_A",
                "DRV5_A",
                "DRV6_A",
                "DRV7_A",
                "DAYROOM_1",
                "DAYROOM_2",
                "ALARM",
                "RUNGUY",
                "NUF1",
                "SUICIDE",
                "WT3",
                "RAD1_A",
                "TV1",
                "YARD",
                "LEAVE",
                "LEO20",
                "BOD1",
                "LSE2",
                "LSE2_A",
                "NOTYT",
                "BOD2",
                "END4_A",
                "LSE1_A",
                "BOD2_A",
                "XTUT2",
                "TELE",
                "BB3",
                "BB2",
                "BB3_A",
                "BB2_A",
                "JUMPOUT",
                "THUNDER",
                "LUPINO",
                "CELL2",
                "WT7",
                "WT8",
                "WT9",
                "PHONE",
                "BEAT",
                "NUE1",
                "LEO18",
                "WAIT1_A",
                "MTP1_A",
                "NEWLIFT",
                "NEWLIFT2",
                "ELEVATORSTOP"
            ]
        ],
        [
            "level" => "A07_2Tolerance_Zone",
            "names" => [
                "STAIRS",
                "PORN",
                "PORNBRK",
                "DAN3",
                "DAN6",
                "OUTRO",
                "OUT1_A",
                "OUT2_A",
                "LOCKEDDOOR_CHAIN",
                "WHR1",
                "WHR2",
                "WHR3",
                "WHR1_A",
                "LEO1",
                "DAN1",
                "LEO6",
                "LEO8",
                "DAN4",
                "DAN5",
                "DAN7",
                "INTRO",
                "HLD1_A",
                "HLD2_A",
                "HLD3_A",
                "HLD4_A",
                "TRM1_A",
                "WV1JA5",
                "WV1JA6",
                "TRMP1"
            ]
        ],
        [
            "level" => "A03_Neighbourhood",
            "names" => [
                "WIFE1",
                "LEO8",
                "WIF1_A",
                "WIF2_A",
                "WHYTE",
                "INTRO",
                "LEO1",
                "DAN1",
                "LEO2",
                "COP7",
                "TAR1_A",
                "MIA1",
                "MIA2",
                "MIA3",
                "MIA4",
                "MIB1",
                "MIB2",
                "MIB3",
                "MIB4",
                "WIA1",
                "WIA2",
                "WIA3",
                "WIA4",
                "WIB1",
                "WIB2",
                "WIB3",
                "WIB4",
                "HP5",
                "HP6",
                "HP10",
                "COP4",
                "HP7",
                "WIB5",
                "MIB5",
                "MIA6",
                "MIA7",
                "MIB6",
                "MIB7",
                "WIA6",
                "WIA7",
                "WIA8",
                "MIB8",
                "GUARD1",
                "COP1",
                "COP5",
                "CHA3_A",
                "GUARD2",
                "COP3",
                "COP2",
                "HP8",
                "FENCE",
                "LEO4",
                "HP9",
                "MIA9",
                "WIB10",
                "HE01",
                "HE02",
                "HE03",
                "HE04",
                "HE05",
                "HE06",
                "HP1",
                "HP2",
                "HP3",
                "CARALARM",
                "CARALARM1",
                "CARALARM2",
                "CARALARM3",
                "GLASS_BREAK",
                "SWAT1"
            ]
        ],
        [
            "level" => "A17_Creepy_Farm",
            "names" => [
                "SNIPE",
                "SHO1",
                "WINCH",
                "HAY2",
                "HAYDROP",
                "FAL1",
                "HAY1"
            ]
        ],
        [
            "level" => "A14_SugarFactory",
            "names" => [
                "WHISTLE",
                "RUSTLE",
                "ROOM1",
                "ROOF",
                "HARBOUR",
                "SCREAM",
                "LEO6",
                "OUTRO",
                "MICH14",
                "MICH15",
                "MACHPUZ",
                "BUZZER1",
                "WEIGHT_ON",
                "WEIGHT_OFF",
                "MICH12",
                "DR_GEN_LOCKED",
                "LOCKEDDOOR",
                "PROJ3",
                "KMACH1_LP",
                "LEO2",
                "STAIR1",
                "MICH11",
                "STAIR2",
                "PM8",
                "PM8_A",
                "PROJ2",
                "PM9",
                "PM10",
                "PM9_A",
                "PM10_A",
                "PROJ1",
                "PM5",
                "PM6",
                "MIKESHOT",
                "MANGLE1",
                "POWER",
                "HP2",
                "LEO4",
                "FLAIR1",
                "FLAIR2",
                "MICH3",
                "MICH10",
                "PM4",
                "MICH16",
                "MICH1",
                "MICH2",
                "MICH5",
                "MICH6",
                "MICH8",
                "HE03",
                "HE01",
                "HE02",
                "HE04",
                "HP1",
                "HP3",
                "LEO1",
                "LEO7",
                "LEO3",
                "INTRO",
                "SPLASH",
                "LEO5",
                "HU03",
                "STAIRM",
                "MICH13"
            ]
        ],
        [
            "level" => "A10_Brothel",
            "names" => [
                "SEX1",
                "SEX2",
                "SEX3",
                "SEX4",
                "SEX5",
                "SEX6",
                "SEX7",
                "LAUNDRY1",
                "ROOF",
                "SHAFT",
                "WINDOW1",
                "PHN1",
                "HOOK",
                "POWER",
                "CLI2",
                "SEXPUZ1",
                "SEXPUZ2",
                "SEXPUZ3",
                "SEXPUZ4",
                "SEXPUZ5",
                "sound",
                "DG12",
                "DG3",
                "DG4",
                "DG5",
                "DG11",
                "DG6",
                "JU1",
                "JU2",
                "JU3",
                "JU5",
                "LIFT",
                "JONA2",
                "JONA3",
                "JONA12",
                "JONA13",
                "sample",
                "DG1",
                "DAN3",
                "DG2",
                "DG8",
                "DG9",
                "DG10",
                "UNLOCK",
                "START",
                "SNORE"
            ]
        ],
        [
            "level" => "A18_Manor",
            "names" => [
                'AV1DS1',
                'BEAT',
                'BEAT2',
                'BLOCK',
                'BOD1',
                'BOD2',
                'BVIC1',
                'DAN10',
                'DAN11',
                'DAN13',
                'DAN5',
                'DAN7',
                'DANR1',
                'DYINGGUY',
                'ESCAP',
                'ET1',
                'ET2',
                'ET3',
                'ET4',
                'FBEDS',
                'FRGHT',
                'HIDE',
                'HORN',
                'HUNTR',
                'KILL',
                'LEAVE',
                'LEO10',
                'LEO16',
                'LEO18',
                'LEO20',
                'LEO21',
                'LEO22',
                'LEO23',
                'LEO24',
                'LEO31',
                'LEO32',
                'LEO33',
                'LEO34',
                'LEO35',
                'LEO36',
                'LEO37',
                'LEO40',
                'LEO41',
                'LEO44',
                'LEO45',
                'LEO50',
                'LEO53',
                'LEO8',
                'LEO9',
                'LGHTN1',
                'LGHTN2',
                'LGHTN3',
                'LIFT1',
                'LN1',
                'LN2',
                'LN3',
                'LOONIES',
                'LSE2',
                'LUPINO',
                'MELE3',
                'ML11',
                'ML12',
                'MLT1',
                'MLT2',
                'MLT3',
                'MLT9',
                'MONGS',
                'MONGS2',
                'NATTACK5',
                'NEWLIFT',
                'NEWLIFT2',
                'NOTYT',
                'NUA3',
                'NUA4',
                'NUE1',
                'NURSELIFT',
                'PHONE1',
                'PICK2',
                'PUSH',
                'RADIO1',
                'RADIO2',
                'RADIO3',
                'RIOT1',
                'RUNGUY',
                'SFAIL1',
                'SFAIL2',
                'SFAIL3',
                'SRE2',
                'STEAM',
                'SUICIDE',
                'SYR1',
                'TELE',
                'TRUCK',
                'WACKO3',
                'WT2',
                'WT3',
                'WT7',
                'WT8',
                'WT9',
                'YARD',
                'DAN19',
                'LEO3',
                'LEO7',
                'DAN8',
                'DAN9',
                'DAN10',
                'DAN11',
                'DAN12',
                'DAN13',
                'DAN14',
                'DAN17',
                'DAN18',
                'FAIL',
                'OUTRO',
                'COM1_A',
                'COM2_A',
                'EXC1_A',
                'HU01',
                'WHYTE',
                'DAN1',
                'FR01',
                'DAN2',
                'LEO1',
                'DAN3',
                'LEO2',
                'DAN5',
                'LEO4',
                'DAN6',
                'LEO5',
                'DAN7',
                'LEO6',
                'DAN4',
                'INTRO',
                'HLL1_A',
                'SCREAM'
            ]
        ],
        [
            "level" => "A07_Tolerance_Zone",
            "names" => [
                "PLANK",
                "WD3",
                "DAN10",
                "FLASH1",
                "LEO6",
                "FLASH2",
                "JIZZMUS",
                "PRP2",
                "HU02",
                "HU03",
                "HU04",
                "HU05",
                "PORN",
                "STEPS",
                "WD1",
                "WD2",
                "HU01",
                "WINDOW",
                "DAWG1",
                "PIDG1",
                "ROOF1",
                "V10",
                "V06",
                "V11_A",
                "V11_B",
                "V11_C",
                "V11_D",
                "V01",
                "V03",
                "OUT2",
                "OUTRO",
                "BEAT2",
                "COP1",
                "TORNADO",
                "BEAT1",
                "RK1",
                "CARALARM",
                "KNG1",
                "V09",
                "GUARDS",
                "LEO5",
                "RK2"
            ]
        ],
        [
            "level" => "A15_Cemetery",
            "names" => [
                "name",
                "WIFEC4",
                "WIFEC5",
                "DANW1",
                "DANW2",
                "DANW3",
                "WIFEC2",
                "WIFEC3",
                "LEO2",
                "DAN3",
                "LEO8",
                "DAN4",
                "LEO9",
                "DAN5",
                "OUTRO",
                "WHYTE",
                "LEO1b",
                "DAN1",
                "LEO3",
                "LEO5",
                "LEO4",
                "ET_L06A",
                "CP_P09A",
                "MCH1",
                "CM_L12A",
                "LEO7",
                "WIFEC1",
                "DAN2",
                "INTRO",
                "CRYPT1",
                "ZOMB",
                "CRYPT2",
                "GATE",
                "WIFEM"
            ]
        ],
        [
            "level" => "A06_CIA_Trap",
            "names" => [
                "DAFILTH2",
                "DAFILTH1",
                "LEO6",
                "CHD2",
                "LEO11",
                "ROOF",
                "HELI7",
                "LEO7",
                "SHOOT",
                "StreamName",
                "BHD10",
                "BHD11",
                "FIRE_UZI",
                "OUTRO",
                "FENCE",
                "BHD9",
                "ESCAPE",
                "BHD8",
                "LOCKEDDOOR",
                "STDOOR",
                "HE02",
                "HE03",
                "HE04",
                "LEO9",
                "LEO4",
                "HELI_FIRE",
                "BULLET_IMPACT_METAL",
                "BULLET_RICOCHET_WOOD",
                "LEO2",
                "LEO3",
                "LEO5",
                "BHD1",
                "BHD3",
                "BHD4",
                "BHD5",
                "BHD6",
                "BHD7",
                "BHD2",
                "HE01",
                "SCREAM"
            ]
        ],
        [
            "level" => "A12_Plaza",
            "names" => [
                "INTRO_A",
                "DAN1_A",
                "LEO1_A",
                "LEO1_B",
                "AMBSHOT",
                "DETECT",
                "MOVOU",
                "LIFT_LP",
                "HE04",
                "HE01",
                "HE03",
                "HE05"
            ]
        ],
        [
            "level" => "A04_SM_Nightclub",
            "names" => [
                "GMP3",
                "GMP4",
                "DRILL1",
                "DRILL2",
                "DRILL3",
                "PISSING",
                "PERV33",
                "PERV31",
                "LE02",
                "MUSIC",
                "OUTRO",
                "PROD",
                "DRILL",
                "HU06",
                "WEIGHTON",
                "CHAIR",
                "PPD1",
                "PPD2",
                "PPD3",
                "LEO11",
                "LEO4",
                "V01",
                "JUDY",
                "CF03",
                "TOILET",
                "FLASH2",
                "LEO10",
                "V03",
                "LEO12",
                "PERV13",
                "DANCE",
                "STRIP1",
                "FLASH1",
                "ENT",
                "HEAD",
                "SAW",
                "DJ06",
                "JUDY1",
                "PERV32",
                "DAN4",
                "BUZZERDENY",
                "BUZZERACCEPT"
            ]
        ],
        [
            "level" => "A02_The_Old_House",
            "names" => [
                "SECON",
                "BASEM",
                "GROUN",
                "LEO7",
                "NOSYRING",
                "CROW2",
                "LEO9",
                "FLSHBK",
                "LEO1",
                "DAN1",
                "Leo2",
                "Dan2",
                "LEO3",
                "HOUSE",
                "DAN9",
                "DAN12",
                "DAN3",
                "LEO4",
                "LEO8",
                "LEO5",
                "DAN10",
                "HUNT1",
                "GHOSON4",
                "BGCRSH",
                "SEQ2",
                "WD11",
                "CHK4",
                "CHK3",
                "INTRO",
                "HUNTNIS1",
                "FLASH1",
                "FLASH2",
                "HAUNT1",
                "BOY",
                "HALL",
                "FLASHPIC",
                "HAUNT3",
                "OLD_HOUS",
                "STATIC2",
                "STATIC1",
                "CHK1",
                "KDOR1",
                "SCURRY",
                "SOB1",
                "PICKUP_WEAPON",
                "PICTURESMASH",
                "SWING",
                "FLRCRK1"
            ]
        ],
        [
            "level" => "A11_Medicine_Lab",
            "names" => [
                "KILLP",
                "INTRO",
                "HYPNO",
                "FLASHBACK1",
                "TH1",
                "TH21",
                "TH23",
                "TH3",
                "TH22",
                "S3",
                "L1",
                "L2",
                "L3",
                "S1",
                "S2",
                "S4",
                "RETCONF",
                "OPENVENT",
                "GUARD1",
                "Tannoyexplode",
                "DAN1",
                "LEO4",
                "DAN2",
                "LEO5",
                "TV1",
                "LEO2",
                "MEDDOG",
                "CONF",
                "COVER",
                "HU01_A",
                "PM4",
                "SG4",
                "Nu1",
                "SUR2",
                "SUR3",
                "RETINA",
                "NITRUS",
                "LOCK1",
                "FAIL_A",
                "PICKT_A",
                "GETHM0",
                "GETHM1",
                "GETHM2",
                "GETHM3",
                "LOCKEDDOOR",
                "PM5A",
                "HYPST",
                "LEO1",
                "LEO3",
                "GUARD2",
                "CONV1",
                "CONV2",
                "CONV3",
                "PICK9_A",
                "PM5B",
                "TANOFF",
                "PM5C",
                "PICK1_A",
                "PICK3_A",
                "PM6",
                "HALL",
                "CAPT1",
                "CAPT2",
                "LEO6",
                "OUTRO",
                "SUR1",
                "PICK4",
                "SUR4",
                "PICK5",
                "PICK1",
                "PICK5_A",
                "PICK6_A",
                "PM5D",
                "SG2",
                "PM1",
                "SG3",
                "PM2_A",
                "PM2_B",
                "MDOC",
                "GUARD3"
            ]
        ],
        [
            "level" => "A09_Burn",
            "names" => [
                "LEO4",
                "LEO2",
                "PTR5",
                "INSIDE1",
                "INSIDE2",
                "PTR5_A",
                "LEO5",
                "SPRINK1",
                "SPRINK2",
                "SPRINK3",
                "POWER",
                "SLIDE_OPEN",
                "LEO8",
                "DECOY",
                "PTR1",
                "FIRE",
                "LEO7",
                "LEO3",
                "GUARDS1",
                "SEC1",
                "SEC2",
                "SEC3",
                "SEC4",
                "SEC5",
                "ALARM",
                "LEO1",
                "LOCKEDDOOR_CHAIN",
                "WARE",
                "BIRD",
                "DETECT",
                "TODO",
                "LEO6",
                "LEO6_A"
            ]
        ],
        [
            "level" => "A16_TV_Studio",
            "names" => [
                "CAROUT",
                "V01",
                "MACHINER",
                "TVSPAWN",
                "BADCLOWN",
                "CARINT1",
                "CARINT2",
                "SMALLLIFT",
                "LOCKEDDOOR_CHAIN",
                "SITKILL1",
                "SITKILL2",
                "SITKILL3",
                "SITKILL4",
                "SITKILL5",
                "SITKILL6",
                "SITKILL7",
                "SITKILL8",
                "DAN2",
                "LEO1",
                "DAN3",
                "LEO2",
                "TRAILER",
                "KATANA",
                "BOD1_A",
                "BOD1_B",
                "BOD1_C"
            ]
        ]
    ];

    /**
     * Taken from 0x525D60
     */
    public $weapon = [
        "Tripwire_(CT)",
        "Gasoline_(CT)",
        "Water_Bottle_(CT)",
        "Lighter_(CT)",
        "Cash_(CT)",
        "Torch_(CT)",
        "N_Vision_(CT)",
        "Painkillers_(CT)",
        "G_First_Aid_(CT)",
        "Y_First_Aid_(CT)",
        "Speed_Boost_(CT)",
        "Strength_Boost_(CT)",
        "Shooting_Boost_(CT)",
        "Reflexes_Boost_(CT)",
        "Health_Boost_(CT)",
        "fists",
        "K_Dust_(CT)",
        "Hunt_Knife_(CT)",
        "Shard_(CT)",
        "Shard_Piggsy_(CT)",
        "Broken_Bottle_(CT)",
        "Jury_Blades_(CT)",
        "Pipe_(CT)",
        "Cleaver_(CT)",
        "Wooden_Bar_(CT)",
        "Crowbar_(CT)",
        "Sickle_(CT)",
        "NightStick_(CT)",
        "Cane_(CT)",
        "Axe_(CT)",
        "IcePick_(CT)",
        "Machete_(CT)",
        "Small_Bat_(CT)",
        "Pliers_(CT)",
        "Hammer_(CT)",
        "M_B_Bat_(CT)",
        "Shovel_(CT)",
        "W_B_Bat_(CT)",
        "Fire_Axe_(CT)",
        "Chainsaw_(CT)",
        "Hockey_Stick_(CT)",
        "W_B_Bat_Nails_(CT)",
        "Nail_Gun_(CT)",
        "6Shooter_(CT)",
        "Glock_(CT)",
        "Glock_Torch_(CT)",
        "Shotgun_(CT)",
        "Shotgun_Torch_(CT)",
        "Uzi_(CT)",
        "Uzi_Torch_(CT)",
        "Desert_Eagle_(CT)",
        "C_Commando_(CT)",
        "Sniper_Rifle_(CT)",
        "Sniper_Rifle_Silenced_(CT)",
        "Tranq_Rifle_(CT)",
        "SawnOff_Shotgun_(CT)",
        "Chainsaw_Player_(CT)",
        "Grenade_(CT)",
        "Molotov_(CT)",
        "Exp_Molotov_(CT)",
        "Tear_Gas_(CT)",
        "F_Grenade_(CT)",
        "Half_Brick_(CT)",
        "Bottle_(CT)",
        "Can_(CT)",
        "Firecrackers_(CT)",
        "Severed_Head_(CT)",
        "Bag_(CT)",
        "Wire_(CT)",
        "Wooden_Spike_(CT)",
        "Wire_Piggsy_(CT)",
        "Wooden_Spike_Piggsy_(CT)",
        "Rag_(CT)",
        "Chlorine_(CT)",
        "Meths_(CT)",
        "HCC_(CT)",
        "D_Beer_Guy_(CT)",
        "D_Merc_Leader_(CT)",
        "D_Smiley_(CT)",
        "D_Huntlord_(CT)",
        "E_L_Sight_(CT)",
        "S_Silencer_(CT)",
        "Radio_(CT)",
        "Bar_Key_(CT)",
        "Syard_Comb_(CT)",
        "Camera_(CT)",
        "Body_P1_(CT)",
        "Body_P2_(CT)",
        "Prec_Key_(CT)",
        "Prec_Card_(CT)",
        "Prec_Docs_(CT)",
        "Pharm_Hand_(CT)",
        "Est_G_Key_(CT)",
        "Est_A_Key_(CT)",
        "Doll_(CT)",
        "Antidote_(CT)",
        "swipe card",
        "CJ_DOLL1_(CT)",
        "CJ_DOLL2_(CT)",
        "CJ_DOLL3_(CT)",
        "CJ_DVTAPE_(CT)",
        "CJ_HANDYCAM_(CT)",
        "Syringe_(CT)",
        "SledgeHammer_(CT)",
        "Stunprod_(CT)",
        "Pen_(CT)",
        "AcidBottle_(CT)",
        "1HFirearm_(CT)",
        "2HFirearm_(CT)",
        "CUT_THROAT_RAZOR_(CT)",
        "Blowtorch_(CT)",
        "Mace_(CT)",
        "Hedge_Trimmer_(CT)",
        "MetalHook_(CT)",
        "Circular_Saw_(CT)",
        "Cash_Bundle(CT)",
        "Matchbook_(CT)",
        "Noose_(CT)",
        "Camera_(CT)",
        "Porn_(CT)",
        "FlareGun_(CT)",
        "Crossbow_(CT)",
        "newspaper(CT)",
        "milkbottle(CT)",
        "dildo(CT)",
        "katana(CT)",
        "hacksaw(CT)",
        "GolfBall_(CT)",


        "Barrier", // found in wii
        "BLOW_TOR", // found in wii
        "BrokenWindow", // found in wii
        "DOC_TRAN", // found in wii
        "OPEN_GRA", // found in wii
        "PICK_AXE", // found in wii
        "POWER_SAW", // found in wii
        "prop", // found in wii
        "SCYTHE", // found in wii
        "WOODENBLANK", // found in wii (alias for WOODEN_BLANK)
        "WRENCH", // found in wii
        "Stun_prod_(CT)", //found on wii (alias for Stunprod_(CT))

        //env

        'TV2_Big_TV',
        'Harvester',
        'Light_Feature_Or_Prop',
        'Road_Works_Barrier',
        'Broken_Window',
        'Door',
        'Telephone',
        'Wooden_Blank',
        'Wooden_Chair',
        'Fire_Extinguisher',
        'Gascan',
        'Vending',
        'Sink',
        'Oicket',
        'oil_Barrel',
        'Meat_Hook',
        'Man_Hole',
        'Dumpster',
        'Bath',
        'AgentPrime',
        'Mangler',
        'Tombstone',
        'Fuse_Box',
        'Toilet',
        'Fence_Pole',
        'TV',
        'Window',
        'Hangman_Pole',
        'Dentist_Chair',
        'Aztec_Altar',
        'Guillotine',
        'Iron_Maiden',
        'Liquid_Nitrogen',
        'Manhole',


        //bruteforce results
        'Jack',
        'Fist',
        'Propf',
        'Chair',
        'Knife',

        //exe string results
        'Baseball',
        'Syringei',
        'Meathook',
        'Oilbarrel',
        'FireExt',
        'FlashLight',
        'Metal_Hook',
        'Acid_Bottle',
    ];


    public $crc32Hashes = [];

    public function __construct()
    {
        $this->preCalculateHashes();
    }

    /**
     * @param $pathFilename
     * @param $input
     * @param $game
     * @param $platform
     * @return bool
     */
    public static function canPack($pathFilename, $input, $game, $platform)
    {
        return false;
    }


    public function preCalculateHashes()
    {

        foreach ($this->speech as $speech) {
            foreach ($speech['names'] as $name) {
                $hashName = sprintf("scripted\%s\%s\pc_stream.wav", $speech['level'], $name);
                $hashName = strtolower($hashName);
                $this->crc32Hashes['crc_' . Helper::fromIntToHex(crc32($hashName))] = [$hashName, $name];
            }
        }

        foreach ($this->speech as $speech) {
            foreach ($speech['names'] as $name) {
                $hashName = sprintf("scripted\%s\%s\wii_stream.wav", $speech['level'], $name);
                $hashName = strtolower($hashName);
                $this->crc32Hashes['crc_' . Helper::fromIntToHex(crc32($hashName))] = [$hashName, $name];
            }
        }

        foreach ($this->weapon as $weapon) {
            $this->crc32Hashes['crc_' . Helper::fromIntToHex(crc32($weapon))] = [$weapon, $weapon];

            //prepare name by given rule at sub_525D60 (Thx to MAJEST1C_R3)
            if (strpos($weapon, "(") !== false){
                $name = substr($weapon, 0, strrpos($weapon, '('));
            }else{
                $name = $weapon;
            }

            if (substr($name, -1) == "_") $name = substr($name, 0, -1);
            $name = substr($name, 0, 8);

            foreach ([
                'wii_jump', 'wii_normal1', 'wii_normal2', 'wii_normal3',
                'pc_jump',  'pc_normal1',  'pc_normal2',  'pc_normal3'
             ] as $section) {
                $hashName = sprintf("executions\%s\%s.wav", $name, $section);
                $hashName = strtolower($hashName);

                $this->crc32Hashes['crc_' . Helper::fromIntToHex(crc32($hashName))] = [$hashName, $weapon];

            }
        }
    }

    /**
     * @param NBinary $binary
     * @param $game
     * @param $platform
     * @return array
     */
    public function unpack(NBinary $binary, $game, $platform)
    {

        $entries = $binary->length() / 4;

        $result = [];

        $unknown = [];
        for ($i = 0; $i < $entries; $i++) {
            $crc32 = $binary->consume(4, NBinary::HEX);

            if ($platform == MHT::PLATFORM_WII){
                $crc32 = Helper::toBigEndian($crc32);
            }

            if (isset($this->crc32Hashes['crc_' . $crc32])) {
                $result[] = $this->crc32Hashes['crc_' . $crc32];
            } else {
                $result[] = $crc32;
                $unknown[] = $crc32;
            }
        }

//        echo sprintf("\nNote: %s٪ Solved.\n", number_format((count($result) - count($unknown)) / ($entries) * 100, 2));

////
//        $handle = fopen("4-8char.txt", "r");
//        while (($weapon = fgets($handle)) !== false) {
//                // process the line read.
//
//            $name = trim($weapon);
//            //prepare name by given rule at sub_525D60 (Thx to MAJEST1C_R3)
////            if (strpos($weapon, "(") !== false){
////                $name = substr($weapon, 0, strrpos($weapon, '('));
////            }else{
////                $name = $weapon;
////            }
////
////            if (substr($name, -1) == "_") $name = substr($name, 0, -1);
////            $name = substr($name, 0, 8);
//
//            $hashName = sprintf("executions\%s\pc_normal1.wav", $name);
//            $hashName = strtolower($hashName);
//
//            $crc = Helper::fromIntToHex(crc32($hashName));
//
//            if (in_array($crc, $unknown) !== false){
//                var_dump($hashName);
//            }
//
//        }

//        $this->bruteCrc($unknown);



        return $result;

    }


    private function bruteCrc($hashes){
        for($i = "knife"; 8 > strlen($i); $i++){


            $hashName = sprintf("executions\%s\pc_normal1.wav", $i);
            $hashName = strtolower($hashName);

            $crc = Helper::fromIntToHex(crc32($hashName));

            if (in_array($crc, $hashes) !== false){
                var_dump($hashName);
            }
        }


    }

    /**
     * @param Finder $pathFilename
     * @param $game
     * @param $platform
     * @return null|string
     */
    public function pack($pathFilename, $game, $platform)
    {
    }


}
