#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new \App\Command\PackCommand(
    new \App\Service\Archive\Mls(),
    new \App\Service\Archive\Glg(),
    new \App\Service\Archive\Inst(),
    new \App\Service\Archive\Ifp(),
    new \App\Service\Archive\Grf(),
    new \App\Service\Archive\Bin()
));

$application->add(new \App\Command\GenerateEventsCommand());

$application->add(new \App\Command\UnpackCommand(
    new \App\Service\Archive\Mls(),
    new \App\Service\Archive\Glg(),
    new \App\Service\Archive\Inst(),
//    new \App\Service\Archive\Fsb(),
    new \App\Service\Archive\Grf(),
    new \App\Service\Archive\Ifp(),
    new \App\Service\Archive\Bin()
));

$application->add(new \App\Command\BytecodeExplainCommand(new \App\Service\BytecodeExplain()));


$application->run();