#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

//basic commands
$application->add(new \App\Command\PackCommand());
$application->add(new \App\Command\UnpackCommand());

//extraction helper
$application->add(new \App\Command\MassExtractMlsCommand());
$application->add(new \App\Command\MassExtractionCommand());

//mls compiler helper
$application->add(new \App\Command\BytecodeExplainCommand(new \App\Service\BytecodeExplain()));
$application->add(new \App\Command\GenerateEventsCommand());

$application->run();