<?php
namespace App\Service\Compiler;

use App\Service\Compiler\Tokens\T_ASSIGN;
use App\Service\Compiler\Tokens\T_BEGIN;
use App\Service\Compiler\Tokens\T_BRACKET_CLOSE;
use App\Service\Compiler\Tokens\T_BRACKET_OPEN;
use App\Service\Compiler\Tokens\T_DEFINE;
use App\Service\Compiler\Tokens\T_DEFINE_TYPE;
use App\Service\Compiler\Tokens\T_DEFINE_VAR;
use App\Service\Compiler\Tokens\T_DO;
use App\Service\Compiler\Tokens\T_END;
use App\Service\Compiler\Tokens\T_ENTITY;
use App\Service\Compiler\Tokens\T_FALSE;
use App\Service\Compiler\Tokens\T_FLOAT;
use App\Service\Compiler\Tokens\T_FUNCTION;
use App\Service\Compiler\Tokens\T_IF;
use App\Service\Compiler\Tokens\T_INT;
use App\Service\Compiler\Tokens\T_IS_EQUAL;
use App\Service\Compiler\Tokens\T_IS_GREATER;
use App\Service\Compiler\Tokens\T_IS_NOT_EQUAL;
use App\Service\Compiler\Tokens\T_IS_SMALLER;
use App\Service\Compiler\Tokens\T_LINEEND;
use App\Service\Compiler\Tokens\T_NOT;
use App\Service\Compiler\Tokens\T_NULL;
use App\Service\Compiler\Tokens\T_SCRIPT;
use App\Service\Compiler\Tokens\T_SCRIPT_NAME;
use App\Service\Compiler\Tokens\T_SCRIPTMAIN;
use App\Service\Compiler\Tokens\T_SCRIPTMAIN_NAME;
use App\Service\Compiler\Tokens\T_SELF;
use App\Service\Compiler\Tokens\T_SEPERATOR;
use App\Service\Compiler\Tokens\T_SQUARE_BRACKET_CLOSE;
use App\Service\Compiler\Tokens\T_SQUARE_BRACKET_OPEN;
use App\Service\Compiler\Tokens\T_STRING;
use App\Service\Compiler\Tokens\T_THEN;
use App\Service\Compiler\Tokens\T_TRUE;
use App\Service\Compiler\Tokens\T_VARIABLE;
use App\Service\Compiler\Tokens\T_WHILE;
use App\Service\Compiler\Tokens\T_WHITESPACE;

 class Token {

    const T_IF_END                      = 'T_IF_END';
    const T_WHILE_END                   = 'T_WHILE_END';
    const T_CASE_END                    = 'T_CASE_END';
    const T_SWITCH                      = 'T_SWITCH';
    const T_SWITCH_END                  = 'T_SWITCH_END';
    const T_SCRIPT_END                  = 'T_SCRIPT_END';
    const T_OF                          = 'T_OF';
    const T_CASE                        = 'T_CASE';
    const T_DEFINE_SECTION_ENTITY       = 'T_DEFINE_SECTION_ENTITY';
    const T_PROCEDURE                   = 'T_PROCEDURE';
    const T_PROCEDURE_DEFINE            = 'T_PROCEDURE_DEFINE';
    const T_FORWARD                     = 'T_FORWARD';
    const T_ADDITION                    = 'T_ADDITION';
    const T_SUBSTRACTION                = 'T_SUBSTRACTION';
    const T_DEFINE_SECTION_CONST        = 'T_DEFINE_SECTION_CONST';
    const T_PROCEDURE_NAME              = 'T_PROCEDURE_NAME';
    const T_PROCEDURE_END               = 'T_PROCEDURE_END';
    const T_DEFINE_SECTION_VAR          = 'T_DEFINE_SECTION_VAR';
    const T_DEFINE_SECTION_TYPE         = 'T_DEFINE_SECTION_TYPE';
    const T_TYPE_VAR                    = 'T_TYPE_VAR';
    const T_HEADER_DEFINE               = 'T_HEADER_DEFINE';
    const T_WHITESPACE                  = 'T_WHITESPACE';
    const T_LINEEND                     = 'T_LINEEND';
    const T_DEFINE_TYPE                 = 'T_DEFINE_TYPE';
    const T_SCRIPTMAIN_NAME             = 'T_SCRIPTMAIN_NAME';
    const T_DEFINE_VAR                  = 'T_DEFINE_VAR';
    const T_SCRIPTMAIN                  = 'T_SCRIPTMAIN';
    const T_ENTITY                      = 'T_ENTITY';
    const T_DEFINE                      = 'T_DEFINE';
    const T_SCRIPT                      = 'T_SCRIPT';
    const T_SCRIPT_NAME                 = 'T_SCRIPT_NAME';
    const T_SELF                        = 'T_SELF';
    const T_ELSE                        = 'T_ELSE';
    const T_SQUARE_BRACKET_OPEN         = 'T_SQUARE_BRACKET_OPEN';
    const T_SQUARE_BRACKET_CLOSE        = 'T_SQUARE_BRACKET_CLOSE';
    const T_BRACKET_OPEN                = 'T_BRACKET_OPEN';
    const T_BRACKET_CLOSE               = 'T_BRACKET_CLOSE';
    const T_SEPERATOR                   = 'T_SEPERATOR';
    const T_IF                          = 'T_IF';
    const T_WHILE                       = 'T_WHILE';
    const T_THEN                        = 'T_THEN';
    const T_BEGIN                       = 'T_BEGIN';
    const T_END                         = 'T_END';
    const T_END_ELSE                    = 'T_END_ELSE';
    const T_END_CODE                    = 'T_END_CODE';
    const T_DO                          = 'T_DO';
    const T_TRUE                        = 'T_TRUE';
    const T_FALSE                       = 'T_FALSE';
    const T_FLOAT                       = 'T_FLOAT';
    const T_INT                         = 'T_INT';
    const T_STRING                      = 'T_STRING';
    const T_NULL                        = 'T_NULL';
    const T_ASSIGN                      = 'T_ASSIGN';
    const T_CONDITION                   = 'T_CONDITION';
    const T_OPERATION                   = 'T_OPERATION';
    const T_IS_NOT_EQUAL                = 'T_IS_NOT_EQUAL';
    const T_IS_EQUAL                    = 'T_IS_EQUAL';
    const T_IS_GREATER                  = 'T_IS_GREATER';
    const T_IS_SMALLER                  = 'T_IS_SMALLER';
    const T_NOT                         = 'T_NOT';
    const T_OR                          = 'T_OR';
    const T_AND                         = 'T_AND';
    const T_NIL                         = 'T_NIL';
    const T_FUNCTION                    = 'T_FUNCTION';
    const T_VARIABLE                    = 'T_VARIABLE';
    const T_ENTITY_DEFINE               = 'T_ENTITY_DEFINE';
    const T_IF_VARIABLE                 = 'T_IF_VARIABLE';
}